### PR TITLE
Tweniee:#650 Added X Twitter icon

### PR DESCRIPTION
**Pull request by Tweniee**
@MurhafSousli Please can you review #650 
image

### CODE REVIEW

**Comment by mikecci** [comment]
Any idea when the pull request will be reviewed?

**Comment by mikecci** [comment]
@MurhafSousli

**Comment by MurhafSousli** [comment]
@mikecci Why don't we just change the existing twitter button icon?

**Comment by Tweniee** [comment]
> @mikecci Why don't we just change the existing twitter button icon? 

It good to have options and diversity

**Comment by MurhafSousli** [comment]
@Tweniee I don't think user would use the old twitter icon when the new one is available!

**Comment by Tweniee** [comment]
> @Tweniee Users might not opt for the old Twitter icon if the new one is accessible!

I share your perspective, but I believe there should be room for flexibility without removing already established logos. For instance, the IRCTC website, which handles a significant database, continues to use the old bird logo from Twitter as an example.

Screenshot Capture - 2023-12-15 - 18-30-17

**Comment by AshotAleqsanyan96** [comment]
Hello Friends,  I would like to know when are you planning to merge this pull request and publish a new version of library?

**Comment by MurhafSousli** [comment]
This is fixed in v14 beta

**Pull request closed without merging**
