### PR TITLE
fix(#662): linkedin share button, to be able to share button description as ?text=

### PR DESCRIPTION
**Pull request by mfenderov**
Fix to the https://github.com/MurhafSousli/ngx-sharebuttons/issues/662

### CODE REVIEW

**Comment by MurhafSousli** [comment]
Nope, that issue cannot be fixed because linkedin ignores the description. where did you get this from?

**Comment by MurhafSousli** [comment]
> I've tried it on my website and it works with this fix. For example, https://www.linkedin.com/shareArticle?mini=true&url=google.com&text=hello,world

But this does not show "hello world" as description

**Comment by mfenderov** [comment]
> > I've tried it on my website and it works with this fix. For example, https://www.linkedin.com/shareArticle?mini=true&url=google.com&text=hello,world
> 
> But this does not show "hello world" as description, can you show a screenshot?

I guess there's a misunderstanding from my side.
I thought the purpose of this attribute was to pass a text to a post.
Or is it about the OpenGraph metadata?

**Comment by MurhafSousli** [comment]
It's about LinkedIn that only accepts the url as a parameter, the rest of the properties are fetched from the meta tags

**Comment by mfenderov** [comment]
> It's about LinkedIn that only accepts the url as a parameter, the rest of the properties are fetched from the meta tags

This is not true: `text` is also accepted as a query parameter, but, as I've tested it just now, only for the desktop 🤷

**Pull request closed without merging**
